name: thesis-benedikt

channels:
- conda-forge
- opensourceeconomics

dependencies:
- python=3.7.0
- ipython
- numpy
- numba
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- ruspy
- econsa
- chaospy
- pip
- pip:
  - flake8

