name: thesis-benedikt

channels:
- conda-forge
- opensourceeconomics

dependencies:
- python=3.7
- numpoly==1.0.8
- ipython==7.23.1
- scipy=1.6.1
- numpy
- numba
- pandas
- jupyterlab==3.0.15
- ipykernel
- matplotlib
- seaborn
- ruspy
- chaospy
- pip
- pip:
    - git+git://github.com/OpenSourceEconomics/econsa.git
    # Use shapley.py & morris.py in dir python; not econsa itself until PR through.
    # - install -e C:\Users\admin\Masterarbeit\econsa
    - flake8
    - black
    - pre-commit

