name: thesis-benedikt

channels:
- conda-forge
- opensourceeconomics

dependencies:
- python=3.7.0
- numpoly==1.0.8
- ipython
- scipy=1.6.1
- numpy
- numba
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- ruspy
# - econsa
- chaospy
# - delayed
- pip
- pip:
  - flake8

