name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: thesis-benedikt
           environment-file: environment.yml
           python-version: 3.6
<<<<<<< HEAD
           auto-activate-base: true
    - name: execute notebook
=======
           auto-activate-base: false
    - name: execute main notebook
>>>>>>> ff7fd3c01c1d3972f3532d01eee99ad38c6df64d
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        jupyter nbconvert --execute --ExecutePreprocessor.timeout=120 thesis_project.ipynb
