name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: template-thesis-project
           environment-file: environment.yml
           python-version: 3.6
           auto-activate-base: false
    - name: execute notebook
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        jupyter nbconvert --execute --ExecutePreprocessor.timeout=120 student_project.ipynb
